### ISSUE TITLE
What does the 14 class label mean?

### ISSUE THREAD

**Issue by lgqfhwy** [switchablenorms/DeepFashion_Try_On#11]
In vtion and cp_vton, they both use LIP_JPPNet to get person parsing label, which has 20 class labels. But in your code, your person pasing label only has 14 class, what does 14 class labels mean?
If you map the 20 class to 14 class, could you please provide map dict?  thank you.

**Comment by HAN-YANG-HIT** [comment]
You just need to label your segmentation as ours, and you do not need to care about the missing labels. The final one-hot representation has 14 channels.

**Comment by josearangos** [comment]
@HAN-YANG-HIT  Could you share the segmentation model with the 14 classes?

**Comment by HAN-YANG-HIT** [comment]
You can check the colab link. It contains the pretrained model and the preprocessing details.
