### ISSUE TITLE
how to run train.py 

### ISSUE THREAD

**Issue by ashutoshsoni891** [switchablenorms/DeepFashion_Try_On#12]
Hi there!

Thanks for providing this awesome Repository and make it openSource.I am facing some problems while running TRAIN.PY

Here is the error I am getting  :
**AssertionError: /dockerdata/benchmark_datasets/try_on_training/train_label is not a valid directory**
![Screenshot from 2020-06-05 22-00-48](https://user-images.githubusercontent.com/34247549/83901267-1943a880-a778-11ea-8787-022a38dfbd90.png)

**Comment by ashutoshsoni891** [comment]
I managed it (:+1: 

!python ACGPN_train/train.py --dataroot train_data/

![Screenshot from 2020-06-06 14-49-02](https://user-images.githubusercontent.com/34247549/83941009-8bae9a00-a805-11ea-98d5-351ceb67173a.png)

**Comment by Yijia-Chen** [comment]
How did that work for you? I also face this issue while running the package on Google Colab, and have the following issue:
- If I use "ipython ...", "--dataroot" is not recognized, and the above error occurs.
- If I use "python ...", "--pylab=incline" is not recognized, and GUI not found error occurs.
Please help, greatly appreciate!

**Comment by UESTCrookieLI** [comment]
HI, when I run "python train.py --dataroot XXX"
there is a error:
"FileNotFoundError: [Errno 2] No such file or directory: '/home/liziqi/DeepFashion_Try_On-master/ACGPN_train/models/vgg19-dcbb9e9d.pth'"

where is model vgg19-dcbb9e9d.pth? can i download it?
