### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by zhangxj59** [switchablenorms/DeepFashion_Try_On#2]
Thanks for providing open source code, can you provide test.py ?

**Comment by burning846** [comment]
Just download the dataset and run `train.py`.

**Comment by zhangxj59** [comment]
Thank you

burning846 <notifications@github.com>于2020年3月30日 周一下午1:09写道：

**Comment by kelisiya** [comment]
> Just download the dataset and run `train.py`.

There is a inference model , but  I don't the input:label, label_ref, image_ref；Can you tell me what they mean? Because inference should only need to input model pictures and clothes to successfully predict, but there are 11 parameters in train model .
