### ISSUE TITLE
How to understand pose.json?

### ISSUE THREAD

**Issue by roman22275** [switchablenorms/DeepFashion_Try_On#22]
I am a student and now I am doing some research in computer vision. Your paper and code are of great help! However, I do not understand where the data with poses in json came from. What software did you utilize? I want to use it in my project

**Comment by thaithanhtuan** [comment]
> I am a student and now I am doing some research in computer vision. Your paper and code are of great help! However, I do not understand where the data with poses in json came from. What software did you utilize? I want to use it in my project

As I understand, you can use some pretrained model like open pose to get the pose in json file.

**Comment by hamzanaeem1999** [comment]
@roman22275 
Have you done it , I also  have to take the keypoints . How can i get it ?

**Comment by HAN-YANG-HIT** [comment]
You can check the colab link. It contains the pretrained model and the preprocessing details.
