### ISSUE TITLE
how

### ISSUE THREAD

**Issue by Learningchen** [switchablenorms/DeepFashion_Try_On#23]

**Comment by Learningchen** [comment]
thanks for your contribution on this preject. but i  still havea question about how to use this model with my own data?
for examle, in your test stage, test data includs : color, color mask, edeg, img ,mask ,pose and label sum to 7 files.
how Can i  generate my own test file? thanks for your reading

**Comment by HAN-YANG-HIT** [comment]
You can check the colab link. It contains the pretrained model and the preprocessing details.

**Comment by ErfanMomeniii** [comment]
Hi @LZQhardworker , the file you indicated with colab link in the readme does not exist. Could you please check that?
