### ISSUE TITLE
how to generate your dataset？

### ISSUE THREAD

**Issue by Learningchen** [switchablenorms/DeepFashion_Try_On#24]
thanks for your contribution ！ but i still have a question about how to generate your dataset . for example ,your train_lable and test_lable?

**Comment by HAN-YANG-HIT** [comment]
use some pretrained parsing model

**Comment by Learningchen** [comment]
I mean ,  can your give me some detail about how u preprocess your data? thx for your reply

**Comment by HAN-YANG-HIT** [comment]
One contributor pulled a colab, you may follow the instructions there to generate the data.
