### ISSUE TITLE
Unsatisfactory results of a pretrained model

### ISSUE THREAD

**Issue by roman22275** [switchablenorms/DeepFashion_Try_On#27]
I thought that using your pretrained models mean I can already utilize it for inference. However, i checked clothes warping module alone and it produces results with many artefacts. Is it normal?
![image](https://user-images.githubusercontent.com/41534301/87675542-2b096a00-c780-11ea-863e-2daa4bff6b3c.png)

**Comment by SayleeMore** [comment]
Hey roman22275 can you contact me regarding this? even i am student we can discuss and figure it out. Thanks 
Sayleevmore34@gmail.com

**Comment by HAN-YANG-HIT** [comment]
You may  visualize it in a wrong way. Please check the data type and the value range of the images.
