### ISSUE TITLE
segmentation label

### ISSUE THREAD

**Issue by Learningchen** [switchablenorms/DeepFashion_Try_On#29]
I use LIP model to generate my own dataset, but the label is different with yours , can you tell me which segmentation model you use to generate your dataset?

**Comment by ChongjianGE** [comment]
Hi @Learningchen ,
You can generate the parsing label with any pre-trained models and transfer your output labels in the following correspondence.
0 -> Background
1 -> Hair
4 -> Upclothes
5 -> Left-shoe 
6 -> Right-shoe
7 -> Noise
8 -> Pants
9 -> Left_leg
10 -> Right_leg
11 -> Left_arm
12 -> Face
13 -> Right_arm

**Comment by Becomebright** [comment]
@ChongjianGE How do you get the so-called "Noise"?

**Comment by arvind-iyer** [comment]
@Becomebright they meant 'nose'

**Comment by Becomebright** [comment]
@arvind-iyer I don't think so.

**Comment by levindabhi** [comment]
I have modified the labels accroding to readme in Self Correction Human Parsing repo. https://github.com/levindabhi/Self-Correction-Human-Parsing-for-ACGPN 
Hope you find this helpfull

**Comment by arvind-iyer** [comment]
So "noise" is a category for things that do not fit the other groups?

**Comment by levindabhi** [comment]
[Here](https://github.com/switchablenorms/DeepFashion_Try_On/issues/15#issuecomment-662295710) is comment from [ACGPN repo](https://github.com/minar09/ACGPN) which is same as this repo with few modifications for inference.
