### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by burning846** [switchablenorms/DeepFashion_Try_On#3]
Hi~ I'm trying to reproduce your work on our dataset, so I'd appreciate it if you could tell me the quantity and format of your training dataset, Thank you~

**Comment by HAN-YANG-HIT** [comment]
We used the VITON dataset from CP-VTON's repo, and changed the rgb segment into gray scale. As CP-VTON didn't give out the precise label caption, you may have to highlight the segment data to see the correspondence relationship.
