### ISSUE TITLE
Inconsistancy in the inference code and training code

### ISSUE THREAD

**Issue by rubelchowdhury20** [switchablenorms/DeepFashion_Try_On#33]
According to the paper, one of the inputs to the second generator is supposed to be the output from the first generator, which is dis_label in the code. But in the training coding feeding the dis_label information to the generator, masked_label is fed to the generator which is from the train data segmentation, not the generated one. But in for the inference code, the generated variable is fed to the second generator.
The same thing is found for the inputs to the third generator.
Could you please explain these inconsistencies in training and inference code?

**Comment by HAN-YANG-HIT** [comment]
"We train the proposed modules separately and combine them to eventually output the try-on image."  refer to the paper
