### ISSUE TITLE
Question about the heatmap

### ISSUE THREAD

**Issue by gdut-cjy** [switchablenorms/DeepFashion_Try_On#34]
hey，does this problem with heatmap will influence the model result?
![image](https://user-images.githubusercontent.com/68991221/88902209-78a7cb80-d284-11ea-9c8b-041d99a346c7.png)

**Comment by Becomebright** [comment]
I think it depends. In this case, though the skirt parsing is bad, the tops parsing is not affected. So I guess the model result will not be influenced very much.

**Comment by gdut-cjy** [comment]
> I think it depends. In this case, though the skirt parsing is bad, the tops parsing is not affected. So I guess the model result will not be influenced very much.
Thanks，Have you tried using different human parsers with this model?

**Comment by Becomebright** [comment]
@gdut-cjy  Check this repo: https://github.com/PeikeLi/Self-Correction-Human-Parsing. It performs better, yet still has some problems. We are now using our own human parser, but sadly, I can't share it with you.
