### ISSUE TITLE
Preprocess data?

### ISSUE THREAD

**Issue by Jen-Vu** [switchablenorms/DeepFashion_Try_On#36]
Very nice work! Thanks for sharing. Could you please explain how you pre-process data (e.g. how you derived the data_colormask, data_mask, data_edge, data_pose etc.)? Many thanks!

**Comment by MotiBaadror** [comment]
Hi @Jen-Vu , Did you find anything related to the solution you are looking for?

**Comment by Jen-Vu** [comment]
@MotiBaadror - thank you! Have you been able to run and test this ACGPN model with custom data?

**Comment by MotiBaadror** [comment]
Hi @Jen-Vu , You can find the steps [here](https://github.com/switchablenorms/DeepFashion_Try_On/issues/41#issue-699081238)

**Comment by Yijia-Chen** [comment]
@Jen-Vu What tools do you use to preprocess test_img and test_color to get test_label (person segmentation) and test_edge (cloth mask)?

**Comment by josearangos** [comment]
@MotiBaadror Thanks for share you ideas 

Hi, I want to share the code with i generated the mask for the clothes


```
import numpy as np
import cv2
from matplotlib import pyplot as plt


PATH_IMG ="5.jpg"
image = cv2.imread(PATH_IMG)
mask = np.zeros(image.shape[:2], dtype="uint8")
rect = (1, 1, mask.shape[1], mask.shape[0])
fgModel = np.zeros((1, 65), dtype="float")
bgModel = np.zeros((1, 65), dtype="float")
start = time.time()
(mask, bgModel, fgModel) = cv2.grabCut(image, mask, rect, bgModel,
                                       fgModel, iterCount=10, mode=cv2.GC_INIT_WITH_RECT)
outputMask = np.where((mask == cv2.GC_BGD) | (mask == cv2.GC_PR_BGD),0, 1)
outputMask = (outputMask * 255).astype("uint8")


plt.imshow(image)
plt.title('my picture')
plt.show()

![image](https://user-images.githubusercontent.com/13352055/98868073-910bb280-243d-11eb-842a-7dbde90ff460.png)



plt.imshow(outputMask, cmap="gray")
image
![image](https://user-images.githubusercontent.com/13352055/98868005-7d604c00-243d-11eb-85db-6b723e32a409.png)

```

**Comment by HAN-YANG-HIT** [comment]
We have a colab inference link, you may check the process there.
