### ISSUE TITLE
Problem while testing.

### ISSUE THREAD

**Issue by SayleeMore** [switchablenorms/DeepFashion_Try_On#37]
Hey can you help me with this?  I have used parsing model and openpose what editing should i do ? I am using the normal test.py file given by you. I have added 14 images in test_img.... Same for test_pose and test_label. Added test_colormask and test_mask as it is. And 1 image in test_color and test_edge. [
![IMG_20200809_023715](https://user-images.githubusercontent.com/67450218/89723257-bf679500-d9eb-11ea-9ea3-bd18ac0a19f7.jpg)
](url)

**Comment by MotiBaadror** [comment]
Hi @SayleeMore, Could you show the command you are running? Also share the directory in which you are running the command.

**Comment by amrahsmaytas** [comment]
use beforeusedcommand  --dataroot /pathtodatarootdirectory , it will work
