### ISSUE TITLE
Custom Images Problem

### ISSUE THREAD

**Issue by taliegemen** [switchablenorms/DeepFashion_Try_On#39]
When tried to use custom images with the code, it gives list out of index error.

**Comment by MotiBaadror** [comment]
Hi @taliegemen , Are you using test.py with your custom Images. If yes, Did you modify line 105 in aligned_dataset.py. In that specify number of examples in your test set.
```
test=np.random.randint(# no of examples)
```

**Comment by taliegemen** [comment]
This solves list out of index problem, thank you for that.
