### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered when trying with custom images

### ISSUE THREAD

**Issue by taliegemen** [switchablenorms/DeepFashion_Try_On#42]
![image](https://i.ibb.co/LJNdkLn/13123131312312312312.png)

**Comment by taliegemen** [comment]
This is and error that is caused by segmentation. I changed the segmentation classes of image which is segmentated by LIP_JPPNet. You should probably segment the image with PGN method.

**Comment by iamrishab** [comment]
HI @taliegemen 
I had segmented the image using [PGN](https://github.com/Engineering-Course/CIHP_PGN) but still is facing the same assertion error. Are there any other changes that are required?

**Comment by taliegemen** [comment]
These methods, both PGN and LIP_JPPNet generates images with more classes compared to what is used in pretrained models. So you have to remove extra class informations from the image in order to solve the problem.

**Comment by joel1895** [comment]
How will you solve this extra class information? they are basically pixel values I suppose

**Comment by amandazw** [comment]
> These methods, both PGN and LIP_JPPNet generates images with more classes compared to what is used in pretrained models. So you have to remove extra class informations from the image in order to solve the problem.

how to remove extra class informations from the image？thx for giving some detail imformation

**Comment by taliegemen** [comment]
You can directly use LIP_SSL afaik. I wrote a code which switches LIP_JPPNet generated images to ones in SSL by changing specific colors to other to support the layout for training. If you can't solve the problem you can mail me I can share the code with you. Have a nice day.

**Comment by amandazw** [comment]
> Hi~ I found that I can't solve the problem, plz give me some help, thinks a lot!

**Comment by amandazw** [comment]
> You can directly use LIP_SSL afaik. I wrote a code which switches LIP_JPPNet generated images to ones in SSL by changing specific colors in order to support the layout for training. If you can't solve the problem you can mail me or write from LinkedIn so I can share the code with you. Have a nice day.

Hi~ I found that I can't solve the problem, plz give me some help, thinks a lot!

**Comment by taliegemen** [comment]
If you use LinkedIn you can message me there, if not you can email me: yaraton8@hotmail.com.
