### ISSUE TITLE
How to test your data by using test.py?

### ISSUE THREAD

**Issue by ecarist** [switchablenorms/DeepFashion_Try_On#44]
when I run:
 $ python test.py --dataroot /Data_preprocessing --phase test
I got an error:
$ AssertionError: /Data_preprocessing/test_label is not a valid directory
 can some body tell me why? I just want to use the test.py to test your test data. And I download your test dataset and put it in the folder named Data_preprocessing. why occur such a strange error???

**Comment by ecarist** [comment]
I have solved the above problem, but a new problem has appeared. When I try to test your model, I get the following error after running `python  test.py` :

> TypeError: forward() takes 10 positional arguments but 11 were given

May I ask why ?
 I did not change your model, just to test your data set. Why is there a parameter passing error? 
Are there some minor problems in your test.py code?

**Comment by dubesar** [comment]
@ecarist how did you solve the first error?

**Comment by Tomas1337** [comment]
> @ecarist how did you solve the first error?

I got the first error to resolve by chaning `--dataroot /Data_preprocessing` to `--dataroot ../Data_preprocessing`

**Comment by Tomas1337** [comment]
> when I run:
> $ python test.py --dataroot /Data_preprocessing --phase test
> I got an error:
> $ AssertionError: /Data_preprocessing/test_label is not a valid directory
> can some body tell me why? I just want to use the test.py to test your test data. And I download your test dataset and put it in the folder named Data_preprocessing. why occur such a strange error???

Can you tell me where you found instructions to use `--phase test` as an argument?
