### ISSUE TITLE
Edges appear in the predicted semantic segmentation 

### ISSUE THREAD

**Issue by Mushahid2521** [switchablenorms/DeepFashion_Try_On#45]
I am trying the regenerate the test result. I have tested that my pose model is working fine. 
But I have tested human parsing with both CIHP_PGN model and also with another model trained on LIP dataset. 
Below is the result I am getting and I think the edges in the segmentation is producing the noise in the final output. 
Please help me on this. 
![resized](https://user-images.githubusercontent.com/16560161/93892739-ae11e800-fd0e-11ea-96a2-e80dde4ffbe7.jpg)

**Comment by levindabhi** [comment]
@Mushahid2521 Can you share model/technique you are using for generating test_edge(mask of tryon cloth)?

**Comment by Mushahid2521** [comment]
I just used one of the cloth from the Dataset. 
Could you figure out the edge problem i am facing?

**Comment by levindabhi** [comment]
I tried inferencing cloth from test data and I am not encountering problem you mentioned. For pose keypoints and segmentation map of custom person, I am using [openpose](https://github.com/spmallick/learnopencv/tree/master/OpenPose-Multi-Person) and [human parsing](https://github.com/levindabhi/Self-Correction-Human-Parsing-for-ACGPN) trained on LIP dataset

**Comment by kelisiya** [comment]
> I tried inferencing cloth from test data and I am not encountering problem you mentioned. For pose keypoints and segmentation map of custom person, I am using [openpose](https://github.com/spmallick/learnopencv/tree/master/OpenPose-Multi-Person) and [human parsing](https://github.com/levindabhi/Self-Correction-Human-Parsing-for-ACGPN) trained on LIP dataset

you can use cutout.pro get Image remove matting , the result  with alpha channel , and use threshold in alpha channel get cloth mask.
`import cv2

img = cv2.imread('image.png',cv2.IMREAD_UNCHANGED)
b,g,r,a= cv2.split(img)

a[a<50] = 0
a[a>=50] = 255
cv2.imwrite('alpha.jpg',a)`

**Comment by Mushahid2521** [comment]
@kelisiya can you please to the cutout.pro resource?

**Comment by kelisiya** [comment]
> @kelisiya can you please share the link of cutout.pro resource?
it's a link and you can upload cloth image . I just tried a little bit and thought it was feasible.

**Comment by hamzanaeem1999** [comment]
@levindabhi 
Can you please tell me that How can I do inference on custom image , I have run the project but I am not finding any solution for doing inference . How can i do inference on custom image taken from internet ?

**Comment by LZQhardworker** [comment]
> @levindabhi
> Can you please tell me that How can I do inference on custom image , I have run the project but I am not finding any solution for doing inference . How can i do inference on custom image taken from internet ?

You can use the colab link
