### ISSUE TITLE
Abount the effect of g1

### ISSUE THREAD

**Issue by 07hyx06** [switchablenorms/DeepFashion_Try_On#47]
Hi! Thanks for your great work.
I am confused about the effect of g1. 
Why need to train a g1 to output m_w^S?
Can m_w^S be obtained directly by a human parser?

**Comment by thaithanhtuan** [comment]
m_w^S can not be obtained directly by a human parser. 
When testing, the inshop clothing (sleeve part) is different from the one in human parser, then the arm of output of G1 is different from the one in human parser.

**Comment by HAN-YANG-HIT** [comment]
Nice reply~
