### ISSUE TITLE
Training with a percent of data

### ISSUE THREAD

**Issue by taliegemen** [switchablenorms/DeepFashion_Try_On#48]
Is there an option to only use a percentage of training data available while training? Thanks.

**Comment by MotiBaadror** [comment]
Hi @taliegemen , You can modify the line 212 in train.py 
lets say you want to use 500 sample while training. Then line 212 would be as below
```
 if epoch_iter >= dataset_size:

```

**Comment by taliegemen** [comment]
Thanks a lot!
