### ISSUE TITLE
Dataset problems?

### ISSUE THREAD

**Issue by lgqfhwy** [switchablenorms/DeepFashion_Try_On#5]
Hello, in the dataset, what does the train colormask and train_mask mean?  How to make this? I want to generate it use my own dataset,  Could you please guide me?

**Comment by HAN-YANG-HIT** [comment]
Color mask are strokes and train_mask are random masks, they are used to shade the image to make it incomplete, so that the network learns to inpaint it.

**Comment by lgqfhwy** [comment]
But actually I find you did not use the colormask and train_mask in the inference code.

**Comment by HAN-YANG-HIT** [comment]
yeah，used in train

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: lgqfhwy <notifications@github.com>
发送时间: Wednesday, May 20, 2020 4:45:24 PM
收件人: switchablenorms/DeepFashion_Try_On <DeepFashion_Try_On@noreply.github.com>
抄送: Yang; Han <yanghanhuoying@live.com>; Comment <comment@noreply.github.com>
主题: Re: [switchablenorms/DeepFashion_Try_On] Dataset problems? (#5)


But actually I find you did not use the colormask and train_mask in the inference code.

―

**Comment by HAN-YANG-HIT** [comment]
Please refer to https://github.com/karfly/qd-imd 
![image](https://user-images.githubusercontent.com/58289142/130188535-e31fce02-27ef-4a85-b30c-96a263275eb7.png)
