### ISSUE TITLE
How can you generate the files from the folders ?: test_mask and test_colormask

### ISSUE THREAD

**Issue by josearangos** [switchablenorms/DeepFashion_Try_On#50]
Thank you very much for contributing to this amazing project.

I am trying to test the model with custom images and I have:
  - test_color
  - test_edge
  - test_img
  - test_label
  - test_pose

How can you generate the files from the folders ?:
  - test_mask
  - tes_colormask

Thanks

**Comment by AjayMudhai** [comment]
Hi,as per one user : https://github.com/switchablenorms/DeepFashion_Try_On/issues/5

So I guess any random strokes and masks can be applied. But still looking for more clarity over this. So if you or anyone gets some solution,kindly update.

**Comment by kelisiya** [comment]
> Thank you very much for contributing to this amazing project.
> 
> I am trying to test the model with custom images and I have:
> 
> * test_color
> * test_edge
> * test_img
> * test_label
> * test_pose
> 
> How can you generate the files from the folders ?:
> 
> * test_mask
> * tes_colormask
> 
> Thanks

I currently have some problems, can you share the code about generator test_color, test_edge, test_pose and so on.

**Comment by hamzanaeem1999** [comment]
@kelisiya 
@josearangos 
@ChongjianGE 
@josearangos 

Should we provide all things like test_color, test_edge, test_img etc in inference ? because i think we should pass a single image of cloth and person image ?

**Comment by HAN-YANG-HIT** [comment]
These two random masks and strokes are from _https://github.com/karfly/qd-imd QD-IMD: Quick Draw Irregular Mask Dataset
_
