### ISSUE TITLE
Why in the inference do they paint the nose of the reference image with clothing colors?

### ISSUE THREAD

**Issue by josearangos** [switchablenorms/DeepFashion_Try_On#53]
First I want to tell you that I am very surprised by the excellent results in the inference, thank you very much for contributing with this architecture, I admire you very much.

Also, I would like to know what is the reason why you paint your nose with clothes colors?

How can I get the "Nose" tag in the image-parse?
Could you please share the segmentation model you use? 
I used LIP_JPPNet to generate the segmentation, however it does not have the "Nose" tag that you use.

![image](https://user-images.githubusercontent.com/13352055/95604252-01797b00-0a1d-11eb-8a15-61e10544cf78.png)
![image](https://user-images.githubusercontent.com/13352055/95604290-0a6a4c80-0a1d-11eb-9f71-f51e5b6dc6e3.png)
![image](https://user-images.githubusercontent.com/13352055/95604362-1f46e000-0a1d-11eb-97fa-17f0029f3106.png)
![image](https://user-images.githubusercontent.com/13352055/95604408-2c63cf00-0a1d-11eb-8042-af9077f8b4b0.png)
![image](https://user-images.githubusercontent.com/13352055/95604435-371e6400-0a1d-11eb-92ab-2a2c77741749.png)

**Comment by genghisun** [comment]
Hi, do you find the reason? I have the same problem now.
![image](https://user-images.githubusercontent.com/26201304/97809115-004b0f00-1ca6-11eb-8e0c-2aae4100b3cd.png)
![image](https://user-images.githubusercontent.com/26201304/97809126-1062ee80-1ca6-11eb-8f8c-8e287a106644.png)

**Comment by josearangos** [comment]
maybe it's because this model uses the nose tag in the segmented image, I don't use it

as you generated the label (7 -> Noise) of the segmented image, I use LIP_JPPNet for segmentation, which model did you use?

**Comment by Veronica1997** [comment]
Hi, when I run test.py, I found that the person is randomly dressed clothes in img_color. If I want dress one person by various specific clothes in img_color. What modifition can I do? Thanks a lot!

**Comment by hamzanaeem1999** [comment]
@
josearangos  How did you run the inference on custom images , please share the code . which inputs you have passed to model ?
Thanks

**Comment by hamzanaeem1999** [comment]
@genghisun  How did you run the inference on custom images , please share the code . which inputs you have passed to model ?
Thanks

**Comment by HAN-YANG-HIT** [comment]
u can use the colab
