### ISSUE TITLE
STN Second-Order Difference Constraint

### ISSUE THREAD

**Issue by gauravkuppa** [switchablenorms/DeepFashion_Try_On#56]
I am very impressed with the results of this paper, especially how effective the second-order constraint is at effectively warping cloths. However, I cannot seem to find it in the repository. Has anyone else found it? Where is this constraint implemented?

**Comment by 1702609** [comment]
I have been asking the same question. I cannot find the snipped of the STN and the second-order constraint. @gauravkuppa, have you found it yet?

**Comment by roy-sr** [comment]
https://github.com/switchablenorms/DeepFashion_Try_On/blob/613f76468751d3a54181ddd012a3477c226601cf/ACGPN_train/models/networks.py#L1524-L1527
