### ISSUE TITLE
expected input[1, 44, 256, 192] to have 37 channels, but got 44 channels instead

### ISSUE THREAD

**Issue by Zibin-Z** [switchablenorms/DeepFashion_Try_On#57]
I use openpose to build pose, but when I test, this problem arises, why?
RuntimeError: Given groups=1, weight of size 64 37 3 3, expected input[1, 44, 256, 192] to have 37 channels, but got 44 channels instead

**Comment by AjayMudhai** [comment]
Hi @Zibin-Z . Did u find the solution ? I am struck at the same point.

**Comment by amandazw** [comment]
same problem,but I guesss it because the channel of the image or something else

**Comment by amandazw** [comment]
Found the reason,it because pose are not right,I guess the version of the openpose is not match

**Comment by amandazw** [comment]
> Found the reason,it because pose are not right,I guess the version of the openpose is not match

You got 25 points for openpose, but they need 18 points

**Comment by amandazw** [comment]
> Found the reason,it because pose are not right,I guess the version of the openpose is not match

You got 25 points for openpose, but they need 18 points

**Comment by Zibin-Z** [comment]
ok，thank you
