### ISSUE TITLE
Training setting

### ISSUE THREAD

**Issue by Gogo693** [switchablenorms/DeepFashion_Try_On#58]
Hello,
I am trying to replicate your experiment. How many epochs did you train the model to obtain the results in the paper? Because training for 20 epochs every model as declared I cannot obtain the same results, as well as training for 200.

Thank you.

**Comment by HAN-YANG-HIT** [comment]
It is actually impossible to get all the good results for every test sample. That is why it is still a hard research topic with few real applications. Training more will get better results. Maybe you can try our checkpoints,  results in the paper are generated from them. But of course you cannot get all the results perfect.
