### ISSUE TITLE
self.AR_path  with _labelref?

### ISSUE THREAD

**Issue by Tomas1337** [switchablenorms/DeepFashion_Try_On#60]
```
            dir_AR = '_AR' if self.opt.label_nc == 0 else '_labelref'
            self.dir_AR = os.path.join(opt.dataroot, opt.phase + dir_AR)
            self.AR_paths = sorted(make_dataset_test(self.dir_AR))
```

This is under the aligned_dataset.py

Throws an error that the directory doesn't exist. Sure enough, it doesn't. 
It's also not in the Data_preprocessing.zip.

1. Is this a script generated folder or is this a downloaded folder?
2. What is this for? What is the difference between `dir_AR` and `dir_A`.

Just trying to get the test.py running :)

**Comment by HAN-YANG-HIT** [comment]
maybe you did not specify the directory of dataset
