### ISSUE TITLE
Test on my own image of person and cloth

### ISSUE THREAD

**Issue by lyx0208** [switchablenorms/DeepFashion_Try_On#61]
Does anyone know how can I use the code to test the try-on result with my own image of person and cloth?
Like I have an image of a person and the target cloth, how can I use the code to get the synthesized image.
Thanks in advance!

**Comment by hamzanaeem1999** [comment]
Please answer , if anyone has done it ?

**Comment by hamzanaeem1999** [comment]
@Iyx0208 Have you done it , if yes then please share the code with me ?

**Comment by HAN-YANG-HIT** [comment]
You can use the colab link to try.
