### ISSUE TITLE
Why train options are used in test.py

### ISSUE THREAD

**Issue by lyx0208** [switchablenorms/DeepFashion_Try_On#62]
It works properly but why the train options are used in test.py instead of test options?

**Comment by AniOjha** [comment]
Were you able to run it on a custom image using test.py? If so, could you please tell me the steps? Thanks!

**Comment by lyx0208** [comment]
Sorry, I fail to do so.

发送自 Windows 10 版邮件应用

发件人: AniOjha
发送时间: 2021年2月11日 2:04
收件人: switchablenorms/DeepFashion_Try_On
抄送: lyx0208; Author
主题: Re: [switchablenorms/DeepFashion_Try_On] Why train options are usedin test.py (#62)

Were you able to run it on a custom image using test.py? If so, could you please tell me the steps? Thanks!

**Comment by HAN-YANG-HIT** [comment]
You can check the colab link. It contains the pretrained model and the preprocessing details.
