### ISSUE TITLE
How to get the IS in part 4.4

### ISSUE THREAD

**Issue by lyx0208** [switchablenorms/DeepFashion_Try_On#64]
I've already got a rather nice SSIM result but I just wonder what should I do to get the IS result.

**Comment by HAN-YANG-HIT** [comment]
You can use the code here:
https://github.com/sbarratt/inception-score-pytorch

**Comment by HAN-YANG-HIT** [comment]
![image](https://user-images.githubusercontent.com/58289142/130081173-32471f19-44ad-4399-940f-c81caee46f54.png)
Please remember you should normalize correctly to get the results. Also, the number of splits also influence the results.
