### ISSUE TITLE
Training procedure

### ISSUE THREAD

**Issue by artemkurylev** [switchablenorms/DeepFashion_Try_On#67]
Hi! Thank you for your code and weights. You specified that you trained nets with a different number of epochs. Is it possible to configure it somehow vi options you provided, or I do need some changes in code(for example run train.py for 20 epochs, then freeze some models, and run it for 180 epochs)

**Comment by HAN-YANG-HIT** [comment]
Maybe you need to do it manually, or modify the code. You cannot do it with modifying options
