### ISSUE TITLE
Training results only display shirts?

### ISSUE THREAD

**Issue by PLXIV** [switchablenorms/DeepFashion_Try_On#68]
Hello everyone,

Thank you for your time. I've been trying to train ACGPN with custom data, however the sample results only outputs the shirt, here's  an example:

![image](https://user-images.githubusercontent.com/20990263/111998077-f5413000-8b1b-11eb-9028-d8a01445d7f5.png)

Has anyone encountered similar issues?
Any quick thoughts about why this may be happening?

Thank you very much.

**Comment by cyfr123** [comment]
During the training process, I also had the same problem. Have you solved it? The results of my training are as follows, and the test results with the trained weights are completely different from those in the paper.
Thanks.
![test12600](https://user-images.githubusercontent.com/44593412/121019903-6d8dc800-c7d2-11eb-8f53-2c7ccb75d7b0.jpg)

**Comment by HAN-YANG-HIT** [comment]
You can save as many intermediate results as you want. You need to modify the pix2pixHD.py file and return the 'fake_img' and save it into tensorboard (in 'train.py') to visualize the results.
