### ISSUE TITLE
question about train_pose key_points annotation 

### ISSUE THREAD

**Issue by aba-ai-learning** [switchablenorms/DeepFashion_Try_On#7]
Hello, thanks for the repo and the datasets, I tried to show the key_points on the img with same preifx but found that the points are disorderly. Could you tell me the correct order for the annotation key_point in train_pose repos？

**Comment by aba-ai-learning** [comment]
And I notice that in the readme the key_points is 15,  but in the json file in train_pose repo, the number of axis number is 54 which means there is 27 key points, right?

**Comment by aba-ai-learning** [comment]
I got it, the third number is the score for the point

**Comment by Learningchen** [comment]
> I got it, the third number is the score for the point

can you tell me ， why there is 54 keypotins？and what's the meaning of the score of the point?

**Comment by pruepei** [comment]
> > I got it, the third number is the score for the point
> 
> can you tell me ， why there is 54 keypotins？and what's the meaning of the score of the point?

14 point in total colored @readme, while each point has 3 params, thus the json "pose_keypoints" are shown as follows:

[107.338582677165, 50.0363636363636, 0.883940011262894,
 92.2204724409449, 107.985454545455, 0.594337843358517, 
41.3228346456693, 103.098181818182, 0.542821779847145, 
31.496062992126, 182.458181818182, 0.597596860025078,
 13.3543307086614, 229.701818181818, 0.498640750534832, 
142.614173228346, 113.570909090909, 0.511787667870522, 
142.866141732283, 198.749090909091, 0.523509055376053, 
129.511811023622, 255.767272727273, 0.286236872896552, 
44.8503937007874, 236.683636363636, 0.214285916870722,
 0, 0, 0, 0, 0, 0, 
103.055118110236, 246.458181818182, 0.179784616688266, 
0, 0, 0, 0, 0, 0, 
95.244094488189, 40.2618181818182, 0.920905441045761, 
115.149606299213, 40.0290909090909, 0.965085491538048, 
71.8110236220472, 47.0109090909091, 0.860531315207481, 
125.732283464567, 46.7781818181818, 0.207355766557157]

But I am still wondering what does the 000000 mean by twice... moreover, how can I generate the 14 tuple by an input img.
