### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by shashini4296** [switchablenorms/DeepFashion_Try_On#73]
File "E:\DeepFashion_Try_On\ACGPN_inference\models\pix2pixHD_model.py", line 233, in encode_input
    1, (label_map * (1 - clothes_mask)).data.long().cuda(), 1.0)
  File "C:\Users\SM\AppData\Roaming\Python\Python39\site-packages\torch\tensor.py", line 528, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: CUDA error: device-side assert triggered

How can I fix this issue?

**Comment by amandazw** [comment]
the number of the label is not right

**Comment by shashini4296** [comment]
@amandazw. Thank you very much. 
Can you tell me how to fix it.
I'm creating labels using this repository https://github.com/Engineering-Course/CIHP_PGN.git

**Comment by amandazw** [comment]
I use this one https://github.com/levindabhi/Self-Correction-Human-Parsing-for-ACGPN, it works well

**Comment by SMinosha** [comment]
@amandazw 
I'll try it. 
Thank you very much :)

**Comment by shashini4296** [comment]
@amandazw
I'll try it.
Thank you very much :)
