### ISSUE TITLE
train

### ISSUE THREAD

**Issue by amandazw** [switchablenorms/DeepFashion_Try_On#74]
hi,I use the given models as the pretrained model, and use my own data to train the models.Here is  the result
![000004_0](https://user-images.githubusercontent.com/20120287/117280606-5a1ad480-ae95-11eb-84e3-1ef517fe7d2f.jpg)
![005236_0](https://user-images.githubusercontent.com/20120287/117281236-052b8e00-ae96-11eb-8fb6-2f30663aeed6.jpg)
![000578_0](https://user-images.githubusercontent.com/20120287/117281326-196f8b00-ae96-11eb-80cc-4e70fd0df6ad.jpg)

It seems that the cloth didn't put on at all,can anybody give me some suggestions?Many thx!

**Comment by amandazw** [comment]
the problem was solved

**Comment by subinst1999** [comment]
Hi how did you obtain the pretrained model...when i tried it shows certain .pth files are missing
![acgpn_train](https://user-images.githubusercontent.com/36256066/120272105-1cf60680-c2ca-11eb-81e5-9648994d02ba.JPG)

**Comment by amandazw** [comment]
I just load the exist model

**Comment by subinst1999** [comment]
How did you do that? can you provide the code ..Thanks in advance.

**Comment by amandazw** [comment]
I didn't change any code, just ignore it
