### ISSUE TITLE
How to use InferenceModel?

### ISSUE THREAD

**Issue by tommy19970714** [switchablenorms/DeepFashion_Try_On#76]
[InferenceModel](https://github.com/switchablenorms/DeepFashion_Try_On/blob/613f76468751d3a54181ddd012a3477c226601cf/ACGPN_inference/models/pix2pixHD_model.py#L404) is defined in `pix2pixHD_model.py` file, but [`self.netG`](https://github.com/switchablenorms/DeepFashion_Try_On/blob/613f76468751d3a54181ddd012a3477c226601cf/ACGPN_inference/models/pix2pixHD_model.py#L365), which is called in the [inference](https://github.com/switchablenorms/DeepFashion_Try_On/blob/613f76468751d3a54181ddd012a3477c226601cf/ACGPN_inference/models/pix2pixHD_model.py#L354) function, is not defined.
Is there an example to call the InferenceModel?

**Comment by hamzanaeem1999** [comment]
@tommy19970714 
Have you run this model on custom images ? . I want to test the image of person on cloth taken from Internet . How can I do this ?

**Comment by HAN-YANG-HIT** [comment]
A contributor share a colab to inference custom images. You may use that
