### ISSUE TITLE
Can I use 17 keypoints?

### ISSUE THREAD

**Issue by HansolEom** [switchablenorms/DeepFashion_Try_On#8]
I have a segmentation model and a keypoints model trained with 17 keypoints. 
Your model seems to need 18 keypoints with_center. 
Can I use your model with 17 keypoints?

**Comment by ChongjianGE** [comment]
Hi @HansolEom ,
If you do not mind re-training the overall models, for sure, you can use the model with 17 keypoints output. But we recommend the [Openpose Repo](https://github.com/CMU-Perceptual-Computing-Lab/openpose) to produce the training and testing dataset.

**Comment by hamzanaeem1999** [comment]
@ChongjianGE 
@HansolEom 
I have to take out the keypoints of images and want to save it in a json format , How can i done this , there is no instruction in this github repo ?
