### ISSUE TITLE
detect ours

### ISSUE THREAD

**Issue by CVUsers** [switchablenorms/DeepFashion_Try_On#84]
how to try on our clothes？ are here  Chinese？

**Comment by LZQhardworker** [comment]
Please try the colab

**Comment by CVUsers** [comment]
We can only run demo. Then a new dress comes. At this time, how to generate the data format needed ？

---Original---
From: ***@***.***&gt;
Date: Mon, Dec 13, 2021 09:51 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [switchablenorms/DeepFashion_Try_On] detect ours (Issue #84)




 
Please try the colab
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LZQhardworker** [comment]
the colab can upload any customized upper clothes
