### ISSUE TITLE
Colab Notebook with expired Model Drive Links

### ISSUE THREAD

**Issue by pathakcodes** [switchablenorms/DeepFashion_Try_On#85]
HI,
I was trying given colab notebok in readme,
but model download fails saying `
 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. `

@levindabhi Please help
![image](https://user-images.githubusercontent.com/31039145/158033331-a25195d2-f243-43b3-bd49-8f0452152271.png)

**Comment by levindabhi** [comment]
The error is because of the latest update in google drive and gdown.
You can look into this issue ( https://github.com/wkentaro/gdown/issues/43#issuecomment-621356443 ) or just add `!pip install -U --no-cache-dir gdown --pre` in the first cell of the notebook and try to run again.

**Comment by pathakcodes** [comment]
works, Thanks
