### ISSUE TITLE
Result is not showing

### ISSUE THREAD

**Issue by Manmeet11** [switchablenorms/DeepFashion_Try_On#89]
![a](https://user-images.githubusercontent.com/87129315/176988819-254894cc-4408-489a-ab72-db1c1668b784.png)
I am not able to see the reultant image after uploading cloth and person's image. This error is showing again and again.
Can you please guide how to resolve this?

**Comment by LZQhardworker** [comment]
Maybe you can try to kill the kernel and try again.
