### ISSUE TITLE
test.py showing error

### ISSUE THREAD

**Issue by S-Tensor** [switchablenorms/DeepFashion_Try_On#91]
Hi,
I'm following all instructions which is mentioned in colab notebook, But when i try to run python test.py file.  The following error is shown below. 

![Capture](https://user-images.githubusercontent.com/37458751/178133584-66adde5b-aff7-4b6a-b345-b74a643dd033.JPG)
![Capture3](https://user-images.githubusercontent.com/37458751/178134709-cfc4b421-055d-43b0-91a8-e684aeb30475.JPG)

**Comment by S-Tensor** [comment]
I have resolve the issue

**Comment by Atotem** [comment]
@S-Tensor Hi!, How did you solve it? Greetings.

**Comment by Flatheadman** [comment]
could you share your solution? I have the same issue
